In [8]:
import pandas as pd

In [4]:
df = pd.read_csv("processed_data.csv")

In [5]:
df

,Unnamed: 0,CustomerID,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,0,1,49,0,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,1
1,1,2,43,0,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,1
2,2,3,51,1,2,63.79,Month-to-Month,Fiber Optic,127.58,No,1
3,3,4,60,1,8,102.34,One-Year,DSL,818.72,Yes,1
4,4,5,42,0,32,69.01,Month-to-Month,NaN,2208.32,No,1
...,...,...,...,...,...,...,...,...,...,...,...
995,995,996,42,0,41,37.14,Month-to-Month,Fiber Optic,1522.74,Yes,1
996,996,997,62,0,9,80.93,Month-to-Month,NaN,728.37,No,1
997,997,998,51,1,15,111.72,Month-to-Month,Fiber Optic,1675.80,Yes,1
998,998,999,39,0,68,65.67,One-Year,NaN,4465.56,No,1
999,999,1000,50,0,1,56.67,Month-to-Month,NaN,56.67,No,1

In [7]:
x = df[['Age', 'Gender', 'Tenure', 'MonthlyCharges']]
x.head(10)

   Age  Gender  Tenure  MonthlyCharges
0   49       0       4           88.35
1   43       0       0           36.67
2   51       1       2           63.79
3   60       1       8          102.34
4   42       0      32           69.01
5   42       1      16          119.75
6   60       0      14           80.32
7   52       1       6           58.90
8   40       1      53           49.81
9   50       1      10           61.55

In [9]:
y = df['Churn']
y

0      1
1      1
2      1
3      1
4      1
      ..
995    1
996    1
997    1
998    1
999    1
Name: Churn, Length: 1000, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2)

In [13]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()

In [17]:
x_train = scaler.fit_transform(x_train)

In [18]:
import joblib
joblib.dump(scaler, 'scalar.pkl')

['scalar.pkl']

In [19]:
x_test = scaler.fit_transform(x_test)

In [20]:
from sklearn.metrics import accuracy_score

def modelperf(predictions):
    print('Accruracy score: '.format(accuracy_score(y_test, predictions)))

In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')

In [24]:
model = LogisticRegression()

In [25]:
model.fit(x_train,y_train)

LogisticRegression()

In [26]:
model.predict(x_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1], dtype=int64)